# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3"
    nodejs: "20"

# Build documentation in the "doc/" directory with Sphinx
sphinx:
  configuration: rtest/doc/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#   - pdf
#   - epub

# Python requirements required to build documentation
python:
  install:
    - requirements: rtest/doc/requirements.txt